version: 2.1

jobs:
  build-and-test:
    docker:
      # Imagen principal para el job
      - image: cimg/python:3.9
      
      # Servicio de Redis
      - image: redis:alpine
        name: redis-final
        
         

    steps:
      - checkout
      - setup_remote_docker
      
      # Instalar dependencias
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest redis
      
      # Esperar a que Redis esté listo
      - run:
          name: Esperar inicio de Redis
          command: |
            for i in `seq 150`; do
              nc -z localhost 6379 && echo "Redis está listo" && break
              echo "Esperando Redis..." 
              sleep 1
            done
      
      # Ejecutar pruebas
      - run:
          name: Ejecutar pruebas
          environment:
            REDIS_HOST: redis-final
            REDIS_PORT: 6379
          command: |
            . venv/bin/activate
            pytest tests/
      
      # Construcción de imagen Docker
      - run:
          name: Construir imagen Docker
          command: |
            docker build -t $DOCKER_IMAGE:$CIRCLE_SHA1 .
      
      # Login a Docker Hub
      - run:
          name: Login a Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      
      # Push de imagen
      - run:
          name: Push imagen a Docker Hub
          command: |
            docker push $DOCKER_IMAGE:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main