version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      
      # Instalar dependencias
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
      
      # Ejecutar pruebas
      - run:
          name: Ejecutar pruebas
          command: |
            . venv/bin/activate
            pytest tests/
      
      # Construcción de imagen Docker
      - run:
          name: Construir imagen Docker
          command: |
            docker build -t $isaacam/calculadora_flask:$CIRCLE_SHA1 .
      
      # Login a Docker Hub
      - run:
          name: Login a Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      
      # Push de imagen
      - run:
          name: Push imagen a Docker Hub
          command: |
            docker push $$isaacam/calculadora_flask:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main

