version: 2.1

jobs:
  build-and-test:
    docker:
      # Imagen principal para el job
      - image: cimg/python:3.9
      
      # Servicio de Redis
      - image: redis:alpine
        name: redis-final
        
         

    steps:
      - checkout
      - setup_remote_docker
      
      # Instalar dependencias
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest redis
            pip install pytest-cov
            pip install --upgrade pytest pytest-cov
      
      # Esperar a que Redis esté listo
      - run:
          name: Esperar inicio de Redis
          command: |
            for i in `seq 5`; do
              nc -z localhost 6379 && echo "Redis está listo" && break
              echo "Esperando Redis..." 
              sleep 1
            done
      
      # Ejecutar pruebas
      - run:
          name: Ejecutar pruebas
          environment:
            REDIS_HOST: redis-final
            REDIS_PORT: 6379
          command: |
            . venv/bin/activate
            pytest tests/ \
              --junitxml=test-results/junit.xml \
              --cov=. \
              --cov-report=xml:test-results/coverage.xml \
              --cov-report=html:test-results/coverage-html
      
      # Guardar artefactos de tests
      - store_test_results:
          path: test-results
      
      # Guardar artefactos adicionales
      - store_artifacts:
          path: test-results
          destination: test-reports
      
      # Construcción de imagen Docker
      - run:
          name: Construir imagen Docker
          command: |
            docker build -t $DOCKERHUB_USER/calculadora_app:$CIRCLE_SHA1 .
      
      # Login a Docker Hub
      - run:
          name: Login a Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      
      # Push de imagen
      - run:
          name: Push imagen a Docker Hub
          command: |
            docker push $DOCKERHUB_USER/calculadora_app:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main