version: 2.1

orbs:
  ggshield: gitguardian/ggshield@x.y  # Orb de GitGuardian para escanear secretos

jobs:
  ggshield-scan:
    docker:
      - image: cimg/python:3.9  # Imagen con Python
    steps:
      - checkout  # Obtener código del repo
      - ggshield/scan:  # Ejecutar escaneo con GitGuardian
          name: ggshield-scan
          base_revision: <<pipeline.git.base_revision>>
          revision: <<pipeline.git.revision>>

  build-and-test:
    docker:
      # Imagen principal para el job
      - image: cimg/python:3.9
      
      # Servicio de Redis
      - image: redis:alpine
        name: redis-final

    steps:
      - checkout
      - setup_remote_docker

      # Instalar dependencias
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest redis pytest-cov
            pip install --upgrade pytest pytest-cov
            pip install black ggshield

      - run:
          name: Formatear código
          command: |
            . venv/bin/activate
            black .
            black --check . 

      # Esperar a que Redis esté listo
      - run:
          name: Esperar inicio de Redis
          command: |
            for i in `seq 10`; do
              nc -z localhost 6379 && echo "Redis está listo" && break
              echo "Esperando Redis..." 
              sleep 1
            done
      
      # Ejecutar pruebas
      - run:
          name: Ejecutar pruebas
          environment:
            REDIS_HOST: redis-final
            REDIS_PORT: 6379
          command: |
            . venv/bin/activate
            pytest tests/ \
              --junitxml=test-results/junit.xml \
              --cov=. \
              --cov-report=html:test-results/coverage-html
      
      # Guardar artefactos de tests
      - store_test_results:
          path: test-results
      
      # Guardar artefactos adicionales
      - store_artifacts:
          path: test-results
          destination: test-reports
      
      # Construcción de imagen Docker
      - run:
          name: Construir imagen Docker
          command: |
            docker build -t $DOCKERHUB_USER/calculadora_app:$CIRCLE_SHA1 .
      
      # Login a Docker Hub
      - run:
          name: Login a Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      
      # Push de imagen
      - run:
          name: Push imagen a Docker Hub
          command: |
            docker push $DOCKERHUB_USER/calculadora_app:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - ggshield-scan  # Primero escanea secretos en el código
      - build-and-test:
          requires:
            - ggshield-scan  # Solo se ejecuta si el escaneo de GitGuardian pasa
          filters:
            branches:
              only: main
