version: 2.1

orbs:
  kubernetes: circleci/kubernetes@1.3

jobs:
  build-and-test:
    docker:
      # Imagen principal para el job
      - image: cimg/python:3.9
      
      # Servicio de Redis
      - image: redis:alpine
        name: redis-final
        
    steps:
      - checkout
      - setup_remote_docker
      
      # Instalar dependencias
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest redis
            pip install pytest-cov
            pip install --upgrade pytest pytest-cov
            pip install black
            pip install ggshield
      - run:
          name: Formatear código
          command: |
            . venv/bin/activate
            black .
            black --check . 
      
      # Esperar a que Redis esté listo
      - run:
          name: Esperar inicio de Redis
          command: |
            for i in seq 10; do
              nc -z localhost 6379 && echo "Redis está listo" && break
              echo "Esperando Redis..." 
              sleep 1
            done
      
      # Ejecutar pruebas
      - run:
          name: Ejecutar pruebas
          environment:
            REDIS_HOST: redis-final
            REDIS_PORT: 6379
          command: |
            . venv/bin/activate
            pytest tests/ \
              --junitxml=test-results/junit.xml \
              --cov=. \
              --cov-report=html:test-results/coverage-html \
      
      # Guardar artefactos de tests
      - store_test_results:
          path: test-results
      
      # Guardar artefactos adicionales
      - store_artifacts:
          path: test-results
          destination: test-reports
      
  deploy:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker
      # Construcción de imagen Docker
      - run:
          name: Construir imagen Docker
          command: |
            docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$CIRCLE_SHA1 .
      
      # Login a Docker Hub
      - run:
          name: Login a Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      
      # Push de imagen
      - run:
          name: Push imagen a Docker Hub
          command: |
            docker push $DOCKERHUB_USER/$IMAGE_NAME:$CIRCLE_SHA1
            
  update-k8s-manifests:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar herramientas necesarias
          command: |
            sudo apt-get update
            sudo apt-get install -y git
            pip install PyYAML
            # Configurar SSH
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      # Usar la clave SSH configurada
      - add_ssh_keys:
          fingerprints:
            - "${GIT_SSH_FINGERPRINT}" # La clave que ya configuraste
      - run:
          name: Configurar Git
          command: |
            git config --global user.email "ci-bot@example.com"
            git config --global user.name "CircleCI Bot"
      - run:
          name: Clonar repositorio de manifiestos K8s
          command: |
            # Clonar usando SSH
            git clone git@github.com:IsaacAM50/calculadora-manifiestos-argo.git k8s-manifests
      - run:
          name: Actualizar imagen en manifiesto
          command: |
            cd k8s-manifests
            
            # Crear un script Python y ejecutarlo
            cat > update_manifest.py << 'EOF'
import yaml
import os

# Ruta al archivo de manifiesto
manifest_path = 'manifest/deployment.yaml'  # Ubicación correcta del archivo

# Cargar el manifiesto
with open(manifest_path, 'r') as f:
    manifest = yaml.safe_load(f)

# Actualizar la imagen
for container in manifest['spec']['template']['spec']['containers']:
    if container['name'] == 'flask-app':
        container['image'] = os.environ['DOCKERHUB_USER'] + '/' + os.environ['IMAGE_NAME'] + ':' + os.environ['CIRCLE_SHA1']
        print(f'Actualizando imagen a: {container["image"]}')

# Guardar el manifiesto actualizado
with open(manifest_path, 'w') as f:
    yaml.dump(manifest, f, default_flow_style=False)
EOF

            # Ejecutar el script
            python update_manifest.py
      - run:
          name: Commit y push de los cambios
          command: |
            cd k8s-manifests
            git add .
            git commit -m "Actualizar imagen a $DOCKERHUB_USER/$IMAGE_NAME:$CIRCLE_SHA1"
            # Push usando SSH (que ya debe estar configurado)
            git push origin main

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
      - update-k8s-manifests:
          requires:
            - deploy
          filters:
            branches:
              only:
                - main